<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="botwheel" params="prefix">
    
    <xacro:include filename="inertial_macros.xacro"/>

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="base_mass" value="0.3" /> <!-- arbitrary value for base mass -->
    <xacro:property name="base_width" value="0.1" />
    <xacro:property name="base_length" value="0.1" />
    <xacro:property name="base_height" value="0.05" />
    <xacro:property name="wheel_mass" value="0.3" /> <!-- arbitrary value for wheel mass -->
    <xacro:property name="wheel_len" value="0.020" />
    <xacro:property name="wheel_radius" value="0.015" />
    <xacro:property name="caster_wheel_mass" value="0.1" /> <!-- arbitrary value for caster wheel mass -->
    <xacro:property name="caster_wheel_radius" value="0.015" />
    <xacro:property name="z_offset" value="-${base_height/2}" /> <!-- Space btw top of beam and the each joint -->

        

    <material name="white"> 
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange"> 
        <color rgba="1 0.3 0.1 1" />
    </material>

    <material name="blue"> 
        <color rgba="0.2 0.2 1 1" />
    </material>

    <material name="black"> 
        <color rgba="0 0 0 1" />
    </material>

    <material name="red"> 
        <color rgba="1 0 0 1" />
    </material>

    <!-- Base Link--> 

    <link name="botwheel">
    </link>


    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="botwheel"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

    <!-- Chassis Link -->

    <joint name="chassis_joint" type="fixed">
        <parent link="botwheel"/>
        <child link="chassis"/>
        <origin xyz= "0.05 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="-0.15 0 0.05 "/>
            <geometry>
                <box size="0.3 0.415 0.1"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="-0.15 0 0.05 "/>
            <geometry>
                <box size="0.3 0.415 0.1"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.7" x="0.3" y="0.415" z="0.15">
            <origin xyz="-0.15 0 0.05 " rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Left Wheel Link -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="left_wheel"/>
        <origin xyz= "-0.05 0.2425 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>



    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.0855" length="0.045"/>
            </geometry>
            <material name="black"/>
            <origin xyz="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.0855" length="0.045"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.15" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


     <!-- Right Wheel Link -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="right_wheel"/>
        <origin xyz= "-0.05 -0.2425 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>


    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.0855" length="0.045"/>
            </geometry>
            <material name="black"/>
            <origin xyz="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.0855" length="0.045"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.15" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Caster Wheel -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="-0.3 0 0"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="0.0855"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.0855"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.1" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>

    </link>


    <gazebo reference="caster_wheel">
        <mu1 value="0.0001"/>
        <mu2 value="0.0001"/>
    </gazebo>


    <joint name="laser_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser"/>
        <origin xyz="-0.095 0 0.145" rpy="${pi} ${pi} 0"/>
    </joint>

    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.045"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.08" length="0.045"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.15" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    </xacro:macro>

</robot>

